services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kenmap-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_PATH=/app/data/ftth.db
      # Ganti secret di bawah ini dengan string acak yang aman di production!
      - SESSION_SECRET=VFIsFKQCw1JDKsoG7DlT2vJJggYM1PurdoAG2rqn4i4=
    volumes:
      - kenmap_data:/app/data

volumes:
  kenmap_data:
    driver: local
